### ISSUE TITLE
Error: Tried to create Platform View of Unregistered type

### ISSUE THREAD

**Issue by evandrmb** [endigo/flutter_pdfview#129]
I followed the example code from [here](https://github.com/iampawan/FlutterPDFViewer/blob/master/lib/main.dart)
and I'm getting this eror:

Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.endigo.io/pdfview

# StackTrace
```
E/flutter ( 2418): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 2418): , null, null)
E/flutter ( 2418): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:581
E/flutter ( 2418): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:158
E/flutter ( 2418): <asynchronous suspension>
E/flutter ( 2418): #2      TextureAndroidViewController._sendCreateMessage
package:flutter/…/services/platform_views.dart:1036
E/flutter ( 2418): <asynchronous suspension>
E/flutter ( 2418): #3      AndroidViewController.create
package:flutter/…/services/platform_views.dart:742
E/flutter ( 2418): <asynchronous suspension>
E/flutter ( 2418): #4      RenderAndroidView._sizePlatformView
package:flutter/…/rendering/platform_view.dart:195
E/flutter ( 2418): <asynchronous suspension>
E/flutter ( 2418):
```

**Comment by evandrmb** [comment]
This was solved with a flutter clean and a flutter pub get. Unfortunately I still got error:

```
D/com.shockwave.pdfium.PdfiumCore( 4089): Starting PdfiumAndroid 1.9.0
W/Gralloc4( 4089): allocator 3.x is not supported
W/ilidade_client( 4089): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, reflection, allowed)
D/jniPdfium( 4089): Init FPDF library
D/jniPdfium( 4089): Destroy FPDF library
```

**Comment by Mukhammad1999** [comment]
> I followed the example code from [here](https://github.com/iampawan/FlutterPDFViewer/blob/master/lib/main.dart)
> and I'm getting this eror:
> 
> Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.endigo.io/pdfview
> 
> # StackTrace
> ```
> E/flutter ( 2418): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> E/flutter ( 2418): , null, null)
> E/flutter ( 2418): #0      StandardMethodCodec.decodeEnvelope
> package:flutter/…/services/message_codecs.dart:581
> E/flutter ( 2418): #1      MethodChannel._invokeMethod
> package:flutter/…/services/platform_channel.dart:158
> E/flutter ( 2418): <asynchronous suspension>
> E/flutter ( 2418): #2      TextureAndroidViewController._sendCreateMessage
> package:flutter/…/services/platform_views.dart:1036
> E/flutter ( 2418): <asynchronous suspension>
> E/flutter ( 2418): #3      AndroidViewController.create
> package:flutter/…/services/platform_views.dart:742
> E/flutter ( 2418): <asynchronous suspension>
> E/flutter ( 2418): #4      RenderAndroidView._sizePlatformView
> package:flutter/…/rendering/platform_view.dart:195
> E/flutter ( 2418): <asynchronous suspension>
> E/flutter ( 2418):
> ```

Have the same issue.Followed the same tutorial

**Comment by opsquid** [comment]
I'm having the same problem, any solutions?

**Comment by hajirmujib** [comment]
uninstall app dan run again

**Comment by lat1996vn** [comment]
> I'm having the same problem, any solutions?

uninstall app and run again. Have you try it yet ?
