### ISSUE TITLE
Unable to view PDF

### ISSUE THREAD

**Issue by NiroopNife** [endigo/flutter_pdfview#178]
I was creating a PDF file with tbhe help of the PDF dependency & creating a file. Passed that file to the PDFView but getting an error stating as
```
E/flutter ( 7509): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.endigo.io/pdfview
E/flutter ( 7509): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:197)
E/flutter ( 7509): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:107)
E/flutter ( 7509): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter ( 7509): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 7509): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/flutter ( 7509): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/flutter ( 7509): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/flutter ( 7509): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 7509): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 7509): 	at android.os.Looper.loop(Looper.java:246)
E/flutter ( 7509): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/flutter ( 7509): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7509): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter ( 7509): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter ( 7509): , null, null)
E/flutter ( 7509): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 7509): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 7509): <asynchronous suspension>
E/flutter ( 7509): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1061:18)
E/flutter ( 7509): <asynchronous suspension>
E/flutter ( 7509): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:771:5)
E/flutter ( 7509): <asynchronous suspension>
E/flutter ( 7509): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:191:7)
E/flutter ( 7509): <asynchronous suspension>
E/flutter ( 7509): 
```

**Comment by ahmadzt** [comment]
Same issue here

**Comment by ly2146** [comment]
same to you
