### ISSUE TITLE
Failed to display PDF on iOS

### ISSUE THREAD

**Issue by wijesijp** [endigo/flutter_pdfview#203]
I am using Dart 2.16.2 and DeveTools 2.9,2 for my project 
I am building for iOS 12

On Android it works perfectly.
But on iOS it does not display the pdf file.

It gives following error

```
2022-09-09 18:20:55.040334+0530 Runner[17620:1819255] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: '[plugins.endigo.io/pdfview](http://plugins.endigo.io/pdfview)', null)

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)

#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)

<asynchronous suspension>

#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:236:5)

<asynchronous suspension>

#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:639:44)
```

I followed the instructions in the page. Is there additional steps I have to add?
Can you please provide some advice on how to get it working?

**Comment by kespaldon** [comment]
up

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA
