### ISSUE TITLE
setPage() produces Exception

### ISSUE THREAD

**Issue by l-k22** [endigo/flutter_pdfview#5]
I've noticed that the setPage function produces an exception on Android, no exception is produced on iOS. 
I created a floatingactionbutton to return the user to the 1st page of the pdf like so.
```
FloatingActionButton(
                  mini: true,
                  heroTag: "pdfHome",
                  child: Icon(Icons.home),
                  onPressed: () async {
                    //return to first page
                   await snapshot.data.setPage(0);
                  },
                ),
```
When I press the button (android) the debug console returns the following exception.

```
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): Failed to handle method call
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:124)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at io.endigo.plugins.pdfviewflutter.FlutterPDFView.setPage(FlutterPDFView.java:94)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at io.endigo.plugins.pdfviewflutter.FlutterPDFView.onMethodCall(FlutterPDFView.java:73)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at android.app.ActivityThread.main(ActivityThread.java:6518)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#plugins.endigo.io/pdfview_0( 9605): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/DartMessenger( 9605): Uncaught exception in binary message listener
E/DartMessenger( 9605): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger( 9605): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:124)
E/DartMessenger( 9605): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:219)
E/DartMessenger( 9605): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/DartMessenger( 9605): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/DartMessenger( 9605): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger( 9605): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/DartMessenger( 9605): 	at android.os.Looper.loop(Looper.java:142)
E/DartMessenger( 9605): 	at android.app.ActivityThread.main(ActivityThread.java:6518)
E/DartMessenger( 9605): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger( 9605): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/DartMessenger( 9605): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

```
flutter doctor -v
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E226, locale en-GB)
    • Flutter version 1.5.8 at /Users/xxxxx/Documents/Programming/flutter
    • Framework revision 0ba67226ee (13 days ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.26.1

[✓] Connected device (3 available)
    • ASUS X00TD        • XXXXXXXX                      • android-arm64 • Android 8.1.0 (API 27)
    • IT iPhone • 00000000-00000000000000            • ios           • iOS 12.1.4
    • iPhone Xʀ         • 000000-0000-0000-0000-00000000000• ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by endigo** [comment]
Related https://github.com/flutter/flutter/issues/29092
