### ISSUE TITLE
(android only) PdfView becomes blank on device rotation (portrait -> landscape)

### ISSUE THREAD

**Issue by egodefroy** [endigo/flutter_pdfview#9]
(android only) PdfView becomes blank on device rotation (portrait -> landscape). Does not reappear when the device is rotated back to portrait.

This does not seem to happen when PdfView is in a SizedBox with limited height.

**Comment by zubyf09** [comment]
Same Issue any solution?

**Comment by egodefroy** [comment]
This happens with the example posted with the package.
Just play the example and rotate the terminal
````
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.6.1-pre.32, on Mac OS X 10.13.6 17G7024, locale
    fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (3 available)

• No issues found!
````

**Comment by endigo** [comment]
Hello guys, this is a limitation from a native plugin.
Related to https://github.com/barteksc/AndroidPdfViewer/issues/207
So, you guys try to re-render on device rotate.

**Comment by egodefroy** [comment]
It works if on 'didChangeMetrics' we redefine a new PDFViewController (no more final) and force redrawing the PDFView.

**Comment by endigo** [comment]
@egodefroy post some example code here.

Thanks.

**Comment by l-k22** [comment]
> didChangeMetrics

Could you provide an example, removing final solved another issue for me that caused a blank screen but implementing the didChangeMetrics method hasn't solved the rotation issue.

```
class _PDFScreenState extends State<PDFScreen> with WidgetsBindingObserver {
Completer<PDFViewController> _controller = Completer<PDFViewController>();
PDFViewController _pdfView;
......
@override
  void didChangeMetrics() {
    setState(() { 
      _controller = new Completer<PDFViewController>();
      });
  }
}
```

**Comment by kunalshah** [comment]
I get the same error. Here is the log:

```
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): Failed to handle method call
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:124)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at io.endigo.plugins.pdfviewflutter.FlutterPDFView.setPage(FlutterPDFView.java:119)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at io.endigo.plugins.pdfviewflutter.FlutterPDFView.onMethodCall(FlutterPDFView.java:102)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at android.os.MessageQueue.next(MessageQueue.java:356)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at android.os.Looper.loop(Looper.java:138)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at android.app.ActivityThread.main(ActivityThread.java:6517)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/MethodChannel#plugins.endigo.io/pdfview_0(22432): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
E/DartMessenger(22432): Uncaught exception in binary message listener
E/DartMessenger(22432): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(22432): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:124)
E/DartMessenger(22432): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:219)
E/DartMessenger(22432): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/DartMessenger(22432): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/DartMessenger(22432): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(22432): 	at android.os.MessageQueue.next(MessageQueue.java:356)
E/DartMessenger(22432): 	at android.os.Looper.loop(Looper.java:138)
E/DartMessenger(22432): 	at android.app.ActivityThread.main(ActivityThread.java:6517)
E/DartMessenger(22432): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(22432): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/DartMessenger(22432): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

Here is the repo: https://github.com/iampawan/FlutterPDFViewer

**Comment by MichelMelhem** [comment]
i got the same error,
any work around ?

**Comment by l-k22** [comment]
My work around (not really a work around) is to disable screen rotation whilst viewing PDFs
I have a single widget that handles all my PDFs so I add the following
```
@override
void initState(){
  super.initState();
//Portrait mode only
  SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
  ]);
}
@override
dispose(){
//on dispose allow full orientation
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.landscapeRight,
    DeviceOrientation.landscapeLeft,
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);
  super.dispose();
}
```
However, according to some users on StackOverflow this doesn't work on iPads https://stackoverflow.com/a/50322184/469335

**Comment by egodefroy** [comment]
My work around (not very beautiful...) is based on reinstanciating the controller in didChangeMetrics.
````
@override
  void didChangeMetrics() {
    if (Platform.isAndroid) {
      // for rotations on Android
      pdfController = Completer<PDFViewController>();
      pdfReload = true;
    }
  }
````
and use a Timer in build to force redraw the pdf (code to adapt to your special case)
````
    if (pdfReload) {
      // for rotations on Android
      Timer(Duration(milliseconds: 300), () {
        setState(() {
          pdfReload = false;
         });
      });
    }
...
    var stack = Stack(children: <Widget>[
      pdfReload
          ? Container() // for rotations on Android, force recreate the PDFView
          : PDFView(
              filePath: filePath,
              enableSwipe: true,
              swipeHorizontal: true,
              autoSpacing: false,
              pageFling: false,
              onRender: (_pages) {
                 setState(() {
                  pdfPages = _pages;
                  pdfIsReady = true;
                  pdfReload = false;
                });
              },
              onError: (error) {
               },
              onPageError: (page, error) {
                },
              onViewCreated: (PDFViewController pdfViewController) {
                pdfController.complete(pdfViewController);
              },
              onPageChanged: (int page, int total) {
              },
            ),
      !pdfIsReady
          ? Center(
              child: CircularProgressIndicator(),
            )
          : Container()
    ]);
````

**Comment by MichelMelhem** [comment]
it will be very nice if @endigo  fix this issue

**Comment by MichelMelhem** [comment]
do you know any pdf viewer out there that is more maintained than this one.
Beacause i  didn't find any Pdf viewer that has the same ability.

**Comment by deakjahn** [comment]
You shouldn't expect this automatically from this plugin, the underlying viewer clearly says it's the resposibility of the user to redraw with the current page stored earlier.

I copied the plugin to a local folder because I needed to change a few other things (for instance, instead of a filename, I decided to pass the contents of the PDF in a byte array, this removes the trouble of copying from the Flutter assets to the platform assets, as shown in the example.

So, adding a new channel method to the controller helps us replenish the view:

    void reload(MethodCall call, Result result) {
        String path = (String)call.argument("filePath");
        int page = (int)call.argument("page");
        pdfView.recycle();
        pdfView.fromFile(path).defaultPage(page).load();
        pdfView.fitToWidth(page);
        result.success(true);
    }

(Note that there is a fresh regression [https://github.com/flutter/flutter/issues/33866] that causes these calls to drop java.lang.IllegalStateException: Reply already submitted errors into logcat, it will be fixed in a coming Flutter release).

We also need en extra line in the `FlutterPDFView` constructor as suggested in https://github.com/barteksc/AndroidPdfViewer/issues/328:

        .onRender(new OnRenderListener() {
            @Override
            public void onInitiallyRendered(int pages) {
                pdfView.fitToWidth(pages);
                Map<String, Object> args = new HashMap<>();
                args.put("pages", pages);
                methodChannel.invokeMethod("onRender", args);
            }
        })

And then:

    @override
    void didChangeMetrics() {
      if (Platform.isAndroid) {
        Future.delayed(Duration(milliseconds: 500), () {
          _controller?.reload(_data, _current);
        });
      }
    }

Keep track of `_current` in the `onPageChanged` callback.

**Comment by GENL** [comment]
That's how I solved the problem. I check when the app rotation changes, and I replace the current pdf viewer by a new one. You can also save the current page and redirect the viewer to that page once the viewer has been rebuilt. This is useful when the viewer page is a separated widget. Hope it helped!

```dart
class PdfViewerPage extends StatefulWidget {
  _PdfViewerPageState createState() => new _PdfViewerPageState();
}

class _PdfViewerPageState extends State<PdfViewerPage> {
  Orientation _lastScreenOrientation;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _lastScreenOrientation = MediaQuery.of(context).orientation;
    });
  }

  @override
  Widget build(BuildContext context) {
    // We need to erase and rebuild the viewer when the user changes the screen orientation.
    if (_lastScreenOrientation != null && _lastScreenOrientation != MediaQuery.of(context).orientation) {
      // Completely render the page.
      Future.delayed(Duration(microseconds: 100), _repushViewer);
    }
    return Scaffold(
      resizeToAvoidBottomPadding : false,
      body: PDFView(
        filePath: 'YOUR PDF FILE PATH.',
        onError: (e) {},
      )
    );
  }

  /// Push and replace the viewer page so the page is completely new.
  _repushViewer() {
    Navigator.of(context).pushReplacementNamed(/*YOUR PDF VIEWER PAGE ROUTE */);
  }
}
```

**Comment by isorensen** [comment]
Facing the same issue around here...

**Comment by zaheddec** [comment]
Nice work but this issue is not letting me use it. Cannot go without screen rotation all hacks for screen rotation didn't work :(
Look forward to seeing this get updated.

**Comment by zaheddec** [comment]
> d I replace the current pdf viewer by a new one

How can we redirect the viewer to the current page once the viewer has been rebuilt? Appreciate any idea around it.

**Comment by endigo** [comment]
@zaheddec hello, you can use setPage function.

```
controller.setPage(current);
```

**Comment by zaheddec** [comment]
@endigo Thanks for the replay. I tried to play around with it but could not get any success with it. 
1. I tried to await _controller.future.then((onValue)=>onValue.setPage(5)); in onViewCreated after completer.
2. Tried to add it to onRender callback too but no success.

would really appreciate any idea where to place it. 

Thanks again

**Comment by zaheddec** [comment]
@endigo @GENL Thanks you so much guys. Finally, all worked and set to go for production. Great work, great lightweight library, and great support.

**Comment by GENL** [comment]
Nice to have helped

**Comment by BadTasTe-** [comment]
Hi guys,
this is what i've done to handle this, i'm just using the Orientation builder and re-instantiating the controller on orientation change (controller is not final anymore):

```Dart
Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("PDF"),),
      body: OrientationBuilder(
        builder: (context, orientation) {
          _controller = Completer<PDFViewController>();
          return _buildBody();
        }),
    ); 
```

**Comment by isorensen** [comment]
Dear @zaheddec , how did you replace your hardcoded "5" page to the current last page? I tried to set 'currentPage = page' inside onPageChanged, but it resets when the page is refreshed.
Thank you

**Comment by redbayoub** [comment]
My workaround with the help of @GENL comment.
```

 Orientation _lastScreenOrientation;
 UniqueKey pdfViewerKey = UniqueKey();

@override
  Widget build(BuildContext context) {
 return OrientationBuilder(
                  builder: (ctx, ori) {
                    Orientation newOrientation =
                        MediaQuery.of(context).orientation;
                    if (_lastScreenOrientation != null &&
                        _lastScreenOrientation != newOrientation) {
                      Future.delayed(Duration(microseconds: 100), () {
                        setState(() {
                          _lastScreenOrientation = newOrientation;
                          pdfViewerKey = UniqueKey();
                        });
                      });
                    }
                    return PDFView(
                      key: pdfViewerKey,
                      filePath: cachedFilePath,
                      onPageChanged: (page, total) {
                        setState(() {
                          currPage = page;
                          totalPages = total;
                        });
                      },
                      pageFling: true,
                      onViewCreated: (controller) {
                        if (currPage != null) controller.setPage(currPage);
                      },
                    );
                  },
                );
}
```

but i still don't know why controller.setPage(currPage) not working
and when orientation changes i get
 W/System  ( 4490): A resource failed to call release. 
but it's working

**Comment by akshayyadav76** [comment]
> My workaround with the help of @GENL comment.
> 
> ```
> 
>  Orientation _lastScreenOrientation;
>  UniqueKey pdfViewerKey = UniqueKey();
> 
> @override
>   Widget build(BuildContext context) {
>  return OrientationBuilder(
>                   builder: (ctx, ori) {
>                     Orientation newOrientation =
>                         MediaQuery.of(context).orientation;
>                     if (_lastScreenOrientation != null &&
>                         _lastScreenOrientation != newOrientation) {
>                       Future.delayed(Duration(microseconds: 100), () {
>                         setState(() {
>                           _lastScreenOrientation = newOrientation;
>                           pdfViewerKey = UniqueKey();
>                         });
>                       });
>                     }
>                     return PDFView(
>                       key: pdfViewerKey,
>                       filePath: cachedFilePath,
>                       onPageChanged: (page, total) {
>                         setState(() {
>                           currPage = page;
>                           totalPages = total;
>                         });
>                       },
>                       pageFling: true,
>                       onViewCreated: (controller) {
>                         if (currPage != null) controller.setPage(currPage);
>                       },
>                     );
>                   },
>                 );
> }
> ```
> 
> but i still don't know why controller.setPage(currPage) not working
> and when orientation changes i get
> W/System ( 4490): A resource failed to call release.
> but it's working

because, your setting page in a wrong way...

**Comment by akshayyadav76** [comment]
bool stopBuild = true;
  bool stopBuild2 = false;
  UniqueKey pdfViewerKey = UniqueKey();

 Widget build(BuildContext context) {
    final isLandscape = MediaQuery.of(context).orientation == Orientation.landscape;
    if (isLandscape) {
      if (stopBuild) {
        setState(() {
          _controller = Completer<PDFViewController>();
          pdfViewerKey = UniqueKey();
          stopBuild = false;
          stopBuild2 = true;
        });
      }
    }
    if (!isLandscape) {
      if (stopBuild2) {
        setState(() {
          _controller = Completer<PDFViewController>();
          pdfViewerKey = UniqueKey();
          stopBuild2 = false;
          stopBuild = true;
        });
      }
return pdfView(
key pdfViewerKey ,);
    }



//// when you setPage use do like that

 FutureBuilder<PDFViewController>(
                    future: _controller.future,
                    builder:
                        (context, AsyncSnapshot<PDFViewController> snapshot) {
                      if (snapshot.hasData) {
                        return GestureDetector(
                            onTap: () {
                              snapshot.data.setPage(pages);
                            },
                            child: Text("end"));
                      }
                      return Container();
                    },
                  ),
                ),


 well you can try like this
 it's working perfectly fine for me portrait and landscape even night mode also......
if you want you can check file repo -: college_books/pdfScreen.dart

**Comment by deakjahn** [comment]
I suggest a combination of my previous suggestion and the latest ones. No need to track the orientation, or to use an `OrientationBuilder`, or to force the operation on any other platform than Android:

The only thing needed is:

    @override
    void didChangeMetrics() {
      if (Platform.isAndroid) {
        Future.delayed(Duration(milliseconds: 250), () {
          setState(() => pdfViewerKey = UniqueKey());
        });
      }
    }

and to use the `pdfViewerKey` when building the `PDFView`. This will recreate it when the need arises.

**Comment by egodefroy** [comment]
@deakjahn 
This is close to the work-around I suggested on 27 Jun 2019. A bit simpler though ;-)

**Comment by deakjahn** [comment]
Yep, and also similar to my first idea from last July. That's why I said combination. :-)

**Comment by redbayoub** [comment]
@akshayyadav76  thanks for your solution it work perfectly for me ,but for fit policy i used the default one and it looks great 

@deakjahn i tried your solution but it didn't work for me

**Comment by deakjahn** [comment]
@redbayoub I modified the suggestion, try that. It seems that the rest is also needed to make `didChangeMetrics()` fire.

**Comment by paurakhsharma** [comment]
The easiest workaround I came up with is 

```dart
PDF(
  key: MediaQuery.of(cotext).orientation == Orientation.potrait
          ? ValueKey('potrait')
          : ValueKey('landscape'),
)
```

**Comment by chrislaurie-bs** [comment]
I am trying to implement the solution suggested by [@deakjahn](https://github.com/endigo/flutter_pdfview/issues/9#issuecomment-621162440) - this in null safety. I have a problem with this line:

`WidgetsBinding.instance.addObserver(this);`

I am getting the following error: The method 'addObserver' can't be unconditionally invoked because the receiver can be null.

The didChangeMetrics method is never called when going from portrait to landscape.

**Comment by deakjahn** [comment]
If you're positive that it'll never be null, you use a !:

    WidgetsBinding.instance!.addObserver(this);

If you want to leave it open to not to crash if it is, you use a ?:

    WidgetsBinding.instance?.addObserver(this);

But this isn't PdfView-specific, just the new null-safe Dart, so it might be best for you to read it up. :-))

**Comment by jason19970210** [comment]
@deakjahn 

Hello there, I am trying to implement your method since I modify my pdf viewer page from stateless to stateful.
But once I am working on `didChangeMetrics` then I have no idea where I should declare `pdfViewerKey` and how to use it !!

Or could you making a example for this great method for avoid pdf runs away once android is rotated.

Thanks for help !!

**Comment by deakjahn** [comment]
Just declare it inside your state. I modified the original post with that line.

**Comment by mg142jf** [comment]
I tried my best but i did not figure it out,
Could any one just write the full widget with all the right settings.

**Comment by soni4kirtan6** [comment]
@deakjahn, I am not able to understand where to write reload() function?

> You shouldn't expect this automatically from this plugin, the underlying viewer clearly says it's the responsibility of the user to redraw with the current page stored earlier.
> 
> So, adding a new channel method to the controller helps us replenish the view:
> 
> ```
> void reload(MethodCall call, Result result) {
>     String path = (String)call.argument("filePath");
>     int page = (int)call.argument("page");
>     pdfView.recycle();
>     pdfView.fromFile(path).defaultPage(page).load();
>     result.success(true);
> }
> ```
> 
> (Note that there is a fresh regression [https://github.com/[flutter/flutter/issues/33866](https://github.com/flutter/flutter/issues/33866)] that causes these calls to drop _java.lang.IllegalStateException: Reply already submitted_ errors into logcat, it will be fixed in a coming Flutter release).
> 
> And then:
> 
> ```
> @override
> void didChangeMetrics() {
>   if (Platform.isAndroid) {
>     Future.delayed(Duration(milliseconds: 500), () {
>       _controller?.reload(_data, _current);
>     });
>   }
> }
> ```
> 
> Keep track of `_current` in the `onPageChanged` callback.

**Comment by deakjahn** [comment]
I no longer use endigo's plugin because I needed more and different features (eg. a way to show page pairs at will) but as far as I can remember, I had another suggestion later: https://github.com/endigo/flutter_pdfview/issues/9#issuecomment-621162440

These said there's no need for that `reload()` any more. You only need what's in that later comment, simply to provide a key to the viewer and change that key when the orientation changes. This will already force the system to recreate the view in the platform part automatically.

**Comment by AmirSarraf** [comment]
this force flutter to rebuild the widget, so it works

```code
return OrientationBuilder(
    builder: (context, orientation) {
  return PDFView(
    key: ValueKey('pdf_local_$orientation'),
    filePath: path_to_pdf,
  );
});
```

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by sjmamani** [comment]
In my case, my PdfView becomes blank when the system puts the app in the background or returns the app to the foreground. To resolve that I add `didChangeAppLifecycleState` instead of `didChangeMetrics` method to my `StatefulWidget`:

```


...

@override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (defaultTargetPlatform == TargetPlatform.android &&
        state == AppLifecycleState.resumed) {
      setState(() => pdfViewerKey = UniqueKey());
    }
  }
```
